spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipeApp_prod
    username: recipeApp_prod_user
    password: _123maHim123_
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false